### ISSUE TITLE
The Basics: Server, Gulp, Folder Structure, Etc.

### ISSUE THREAD

**Issue by dansundy** [heliosdesign/angular_template#2]
I figure we can use issues to chat about how to set up this repo.

What would you guys say about always using node to run our local server? (Rather than MAMP, for example). That way if we do need a back end we can just add it on. It seems like we're moving towards running node servers for these apps more than LAMP stacks.

WordPress is the major exception. I updated our [WordPress boilerplate](https://github.com/heliosdesign/helios-wp-boilerplate) at the beginning of the Barrie Radio project. So look at that for WP.

I'd be happy to start working on the Gulp setup for it if so.

D

**Comment by heliosdesign** [comment]
I'd sooner leave the M/LAMP thing as is for now, just that I'm node entirely convinced that is a good idea to run a node server as a production web server. could be convinced otherwise, but also wondering if complicating vs simplifying at this point

**Comment by dansundy** [comment]
Good point. Keeping things as simple and familiar as possible is probably the way to go.

I'll assign myself the task of setting up Gulp but will keep you all posted on how it's going (Iain and Adrian can see this right)? I also will set up a separate discussion for folder structure when the time comes.

I'm also adding Heather as a collaborator so she can see what's going on.

**Comment by iainmcampbell** [comment]
I’ve pushed up the branch where I started to implement the angular style guide: https://github.com/heliosdesign/angular_template/tree/styleguide

(the style guide: https://github.com/johnpapa/angular-styleguide)

**Comment by iainmcampbell** [comment]
I can also do a branch where we use ui-router, along with a bit of an explanation of how ui-router works.

**Comment by dansundy** [comment]
+1 for ui-router for me.

I have a couple suggestions for folder structure as well. I will comment in a pull request to your styleguide branch, Iain.

It would also be good to define exactly what a `module` is at some point.

**Comment by dansundy** [comment]
Alright. I got caught in branch hell so I just tacked an alternative on to the readme and pushed it up to the styleguide branch.

It's basically the same except that it has folders to allow for multiple views, controllers, directives, etc.

**Comment by heliosdesign** [comment]
thanks Dan. agreed as to definition of module.this seems one of the biggest changes (aka something I don't quite understand yet). anyway we can deal with more tomorrow, along with other things like BOS and Katamon

**Comment by dansundy** [comment]
I think it would be helpful to have a document defining modules but also outlining when and where to use controllers, views, directives, filters, factories/services, values, constants... bla bla bla.

I'll start it and you guys can add/edit.

**Comment by iainmcampbell** [comment]
A module is any feature that is spread across more than one file. It's mostly an organizational technique. The important thing about modules is, I think, to be flexible and scale up. So if you know from the start that a feature is going to be pretty involved, ie have several directives or a bunch of assets, start it as a module. Otherwise just add it to `core`, and if it becomes larger then make it a module.

One of the most important things I took from the angular style guide is the importance of using the right level of complexity. For a simple module, 1–10 files, it's probably not necessary to create a subdirectory structure. But if you have four directives and three sass files, then it's probably useful. Otherwise it just slows things down.

Dan, how were you thinking to use a `views` folder? There are a variety of different things that can constitute a view. If we use ui-router, each view could potentially be its own module.

here is another go at folder structure, with two modules, a small one and a big one:

```
/
  [dotfiles, build tools, etc]
  README.md
  SPEC.md

  /dist
    (compiled build)

  /src

    index.html
    style.sass
    style.css

    /components
      (bower components)

    /modules

      /core
        /assets
          (global assets)
          svgdefs.svg
        /config
          routes.js
        /directives
          global-directive.directive.js
          resize.directive.js
        /sass
          _variables.sass
          _functions.sass
          _base.sass
        app.js
        directives.js
        services.js

      /small-module
        small.directive.js
        small.service.js
        small.template.html
        _small.sass

      /big-module
        /assets
          file.jpg
        /directives
          big1.directive.js
          big2.directive.js
          big3.directive.js
        /sass
          _big.sass
          _big2.sass
        big.controller.js

```

**Comment by dansundy** [comment]
I'm happy with this as a starting point if everyone else is. I may propose changes when jumping into gulp. For example, it might always be good to have a `/sass` folder in the module so I can use `*/sass/**/*.sass` in the `src`.

I also agree with your definition of a module. These should be decided on (as much as possible) when we plan the app. If we were building a blog, modules might be `users`, `posts` and `pages`. Some of our apps&mdash;because often times they aren't structured in a traditional way&mdash;may only have the core module.

As for `views`, perhaps that's a bad name for the folder. `partials` might be more appropriate since that's what we have been calling them. They're the `.html` template files for that module. So a `users` module might have `sign-in.partial.html` and `sign-up.partial.html`.

**Comment by iainmcampbell** [comment]
is there a difference between a partial and a template? or is it just terminology

**Comment by dansundy** [comment]
Just terminology. In the past I have used `partials` for view templates, and `templates` for directive templates. (But that is probably backwards now that I think of it). The styleguide doesn't say specifically, right? It just uses `.html` and names it for whatever calls it? (eg. `example-directive.directive.js` and `example-directive.directive.html`).

**Comment by iainmcampbell** [comment]
I would vote for what the style guide suggests: naming the template according to its corresponding JS file. It makes finding template files very simple.

The issue for me with having a category for views is that with `ui-router` a view can potentially be a pretty small component. It’s not necessarily an entire screenful of content.

**Comment by dansundy** [comment]
Works for me!

**Comment by dansundy** [comment]
Closing this. I think everything here has been addressed.
