### ISSUE TITLE
SVGs

### ISSUE THREAD

**Issue by dansundy** [heliosdesign/angular_template#6]
I would like to take svgdefs one step further. I have been using an awesome system for SVG sprites that I would like to put in place. Essentially all you have to do is put an `.svg` file in a folder and gulp will take it, minify it, convert it to a symbol and then inject it into your index file for use anywhere on the site.

I'm proposing that maybe instead of a folder we can use a naming convention like `example.sprite.svg` or `example.icon.svg` to define which svgs should be injected and which ones we just want to remain as files.

Any objections?

**Comment by iainmcampbell** [comment]
Sounds good to me.
